title = "Fujimori website"
baseURL = "https://shintarofujimori-c4b80.web.app"
languageCode = "ja"
theme = "ananke"
themesDir = "../fujimorishintaro/themes"
resourceDir = "../resources"

DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.ja]
    title = "Fujimori website"
    weight = 1
    contentDir = "content/ja"
  # [languages.fr]
  #   title = "Mon blogue"
  #   weight = 2
  #   contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/shintaroface.png"
  site_logo = ""
  description = ""
  facebook = "https://www.facebook.com/profile.php?id=100008335578490"
  twitter = ""
  instagram = "https://www.instagram.com/shintaro.fujimori/?hl=ja"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/IMG_1038.jpg"
  recent_posts_number = 2